### ISSUE TITLE
Fail to get sold value of product, all is zero

### ISSUE THREAD

**Issue by ChiCongNguyen** [lthoangg/shopee-crawler#8]
Im using crawl_by_shop_url, sold value equals 0 for all products
Could you take a look bro :)

**Comment by lthoangg** [comment]
Checked. It works well but with a little different in meaning. Currently with my tool:
`sold` contains the value of product that has been sold in an amount of time (3 days, 5 days, a week, ...) so the value is correct.
You should test that function with other shops to see objectivity result.

Otherwise, this problem will be fixed in the next version `0.1.7`.
Thanks.

**Comment by ChiCongNguyen** [comment]
So how can I input the exact time window I would like to get the sold value?. I did crawl for at least 10 shops but still got zero. :(
For example:
'https://shopee.vn/hoavinh6789'
'https://shopee.vn/cici_thuongdinhyen'

**Comment by lthoangg** [comment]
I did check and it worked as well as I expected.
You can check my results [here](https://colab.research.google.com/drive/1sFpYzSIcQYAUOJiQyMNl9HFXce4BZiGT?usp=sharing).

If you want a _custom_ crawler, send me an email <letronghoang00@gmail.com> with details.

**Comment by ChiCongNguyen** [comment]
Thanks I did get the result. ;)
